Document: vulkan-loader
Title: Debian vulkan-loader Manual
Author: <insert document author here>
Abstract: This manual describes what vulkan-loader is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vulkan-loader/vulkan-loader.sgml.gz

Format: postscript
Files: /usr/share/doc/vulkan-loader/vulkan-loader.ps.gz

Format: text
Files: /usr/share/doc/vulkan-loader/vulkan-loader.text.gz

Format: HTML
Index: /usr/share/doc/vulkan-loader/html/index.html
Files: /usr/share/doc/vulkan-loader/html/*.html
