Document: vulkan-tools
Title: Debian vulkan-tools Manual
Author: <insert document author here>
Abstract: This manual describes what vulkan-tools is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vulkan-tools/vulkan-tools.sgml.gz

Format: postscript
Files: /usr/share/doc/vulkan-tools/vulkan-tools.ps.gz

Format: text
Files: /usr/share/doc/vulkan-tools/vulkan-tools.text.gz

Format: HTML
Index: /usr/share/doc/vulkan-tools/html/index.html
Files: /usr/share/doc/vulkan-tools/html/*.html
